-- AlterTable
ALTER TABLE "InstanceModel" ALTER COLUMN "cpuNumber" DROP DEFAULT,
ALTER COLUMN "cpuSpeedMhz" DROP DEFAULT,
ALTER COLUMN "memoryInMb" DROP DEFAULT,
ALTER COLUMN "rootDiskSizeInGb" DROP DEFAULT;
