-- AlterTable
ALTER TABLE "InstanceModel"
  ADD COLUMN "cpuNumber" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "cpuSpeedMhz" INTEGER NOT NULL DEFAULT 1000,
  ADD COLUMN "memoryInMb" INTEGER NOT NULL DEFAULT 1024,
  ADD COLUMN "rootDiskSizeInGb" INTEGER NOT NULL DEFAULT 10;
